apiVersion: apps/v1
kind: Deployment
metadata:
  name: b-sim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b-sim
  template:
    metadata:
      labels:
        app: b-sim
    spec:
      containers:
      - name: b-sim
        image: dtkmn/bank-sim:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: b-sim
spec:
  selector:
    app: b-sim
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
